name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /home/my-portfolio-website
            git pull
            npm run build
            rm -rf /var/www/alyasar.dev/*
            mv dist/* /var/www/alyasar.dev/
            rm -rf dist

